const san_pham = [
    {
        "id": 1,
        "ten_sp": "ÁO KIỂU YOUTHFUL SET",
        "mo_ta": "Youthful Set với thiết kế trẻ trung, hiện đại nhưng vẫn thời thượng và sang trọng dành cho nàng công sở thêm vào tủ đồ Xuân - Hè của mình. Set bộ gồm áo vest kiểu kết hợp cùng chân váy xếp ly. Áo cổ V, ngắn tay, kiểu dáng Croptop, được cài bằng khuy bọc. Thiết kế mix cùng MS 31M8688 để tạo set hoàn chỉnh. Sản phẩm kết hợp từ 3 dòng chất liệu Rayon, Poly, Spandex cao cấp, mang đến kết cấu mịn, thoải mái, tạo cảm  giác mềm mại khi chạm vào. Ngoài ra, chất liệu có độ rủ tự nhiên và  khả năng chống thấm nước, thoáng khí mát mẻ dành cho mùa hè.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/a1.webp",
        "anh_2": "../images/a2.webp",
        "anh_3": "../images/a3.webp",
        "gia": 550000
    },
    {
        "id": 2,
        "ten_sp": "ÁO KIỂU BLACK TENCEL SET",
        "mo_ta": "Ưu tiên sự tinh giản mà vẫn đảm bảo các yếu tố sang trọng và thời thhượng khi set bộ đã lựa chọn mix từ áo croptop xuông bên cạnh chân váy A xòe nhẹ. Áo kiểu tay ngắn, cổ điểm thêm các chi tiết ren độc đáo. Tay áo xếp ly tạo kiểu bom nhẹ nhàng, bắt mắt. Lựa chọn mix cùng MS 31M8691 để có outfit hoàn hảo. Thiết kế được may cắt từ 2 dòng chất liệu Tencel, Nylon cao cấp, hút ẩm tốt nên khi mặc vô cùng  thoải mái,  không hề cảm nhận sự bí bách. Bề mặt mịn màng, mềm mại, tạo cảm giác thoáng mát, dễ chịu trong thời tiết Xuân – Hè.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/b1.webp",
        "anh_2": "../images/b2.webp",
        "anh_3": "../images/b3.webp",
        "gia": 500000
    },
    {
        "id": 3,
        "ten_sp": "ÁO SƠ MI CỔ TÀU TAY BỒNG",
        "mo_ta": "Thiết kế sơ mi cổ tàu với nhiều chi tiết cách điệu độc đáo là một sự lựa chọn ưu tiên cho xu hướng thời trang Xuân - Hè tới đây.Thân trước được tạo điểm nhấn qua các hàng nhún bèo nhẹ nhàng kết hợp đính khuy kim loại. Áo dáng suông, tay ngắn bồng nhẹ tạo nên vẻ ngoài trẻ trung, năng động và thời thượng. Áo được làm từ các chất liệu lụa,mang lại cảm giác thoải mái và dễ chịu cho người mặc, đồng thời giữ được hình dáng của áo. Nàng dễ dàng mix áo cùng nhiều kiểu chân váy và quần khác nhau để bắt đầu ngày làm việc mới trong vẻ ngoài tràn đầy năng lượng. ",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/c1.webp",
        "anh_2": "../images/c2.webp",
        "anh_3": "../images/c3.webp",
        "anh_4": "../images/c4.webp",
        "gia": 650000
    },
    {
        "id": 4,
        "ten_sp": "ÁO THUN STAY PHỐI VIỀN",
        "mo_ta": "Áo được làm từ chất liệu cotton, giúp mang lại sự thoải mái và mềm mại cho người mặc.- Áo thun cổ tròn,  tay ngắn, dáng suông. Phần cổ áo được làm điểm nhấn với viền khác màu.  - Thiết kế dễ dàng phối hợp với nhiều loại quần, từ jeans đến shorts, tạo ra những outfits phù hợp cho nhiều dịp khác nhau.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/d1.webp",
        "anh_2": "../images/d2.webp",
        "anh_3": "../images/d3.webp",
        "gia": 450000
    },
    {
        "id": 5,
        "ten_sp": "ÁO POLO CARTOON",
        "mo_ta": "Áo polo thời trang nữ linh hoạt và thoải mái. Thiết kế cổ đức có khuy cài, gấu tay bo nhẹ, trước ngực thêu họa tiết nổi bật.Áo được làm từ chất liệu thun co giãn nhẹ, thoáng khí với đường may chắc chắn, tỉ mỉ tạo nên vẻ bền bỉ và chất lượng.Dễ dàng kết hợp với nhiều kiểu quần như jean, chino hoặc chân váy, tạo nên phong cách thời trang xu hướng. ",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/e1.webp",
        "anh_2": "../images/e2.webp",
        "anh_3": "../images/e3.webp",
        "gia": 590000
    },
    {
        "id": 6,
        "ten_sp": "ÁO SƠ MI PEPLUM VAI KIỂU",
        "mo_ta": "Thiết kế áo sơ mi mềm mại, nhẹ nhàng, thích hợp diện trong mùa Xuân - Hè. Cổ áo được may nếp ly, mang đến vẻ nền nã và nữ tính cho thiết kế. Điểm nhấn đặc biệt là chi tiết xếp vai lệch cùng phần Peplum tinh tế, giúp tôn lên vòng eo thon gọn và làm nổi bật cho vẻ đẹp của sản phẩm.Sản phẩm được kết hợp từ 2 dòng chất liệu Tencel, Rayon cao cấp mang đến bề mặt mịn màng, mềm mại, mượt và bóng. Có độ co giãn nhẹ, thấm hút mồ hôi tốt, thoáng mát, dễ chịuÁo có thể được kết hợp với nhiều trang phục và phụ kiện khác nhau. Bạn có thể phối nó với một chiếc chân váy midi hoặc quần cạp cao để tạo nên một bộ trang phục thanh lịch và nữ tính. Nếu muốn tạo ra một phong cách cá nhân và thời trang hơn, hãy kết hợp áo với một đôi quần jeans và giày cao gót.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/f1.webp",
        "anh_2": "../images/f2.webp",
        "anh_3": "../images/f3.webp",
        "anh_4": "../images/f4.webp",
        "gia": 799000
    },
    {
        "id": 7,
        "ten_sp": "ÁO TENCEL DẬP NỔI NHẤN BÈO",
        "mo_ta": "Thiết kế áo suông, không tay. Cổ V cách điệu cùng dây buộc phần cổ. Phần vai và tay áo cánh tiên được viền nhấn bèo chun. Chất liệu lụa phù hợp cho thời tiết ngày hè.Thiết kế áo kiểu không tay luôn được các quý cô ưu ái mỗi khi hè sang. Chất liệu lụa nhẹ nhàng với họa tiết dập nổi mang đến vẻ đẹp sang trọng, tinh tế. Điểm nhấn giúp cho chiếc áo trở nên nổi bật hơn là phần bèo nhún trên vai, góp phần tạo nên vẻ ngoài nữ tính, duyên dáng cho phái đẹp",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/g1.webp",
        "anh_2": "../images/g2.webp",
        "anh_3": "../images/g3.webp",
        "gia": 750000
    },
    {
        "id": 8,
        "ten_sp": "ÁO LỤA CỔ CAO PHỐI NƠ",
        "mo_ta": "Áo dáng suông, cổ tròn, cao tạo kiểu buộc nơ. Tay áo lửng, hơi phồng nhẹ. Phía trước là hàng khuy kim loại trắng may cách điệu. Chất liệu lụa mỏng mát, có độ xuyên thấu nhẹ.Thiết kế này chắc chắn sẽ khiến những quý cô công sở của IVY moda cảm thấy yêu thích. Cổ áo cao buộc nơ thanh lịch. Dáng áo suông với tay phồng sang trọng rất phù hợp để nàng diện sơ vin cùng chân váy hoặc quần dài.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/h1.webp",
        "anh_2": "../images/h2.webp",
        "anh_3": "../images/h3.webp",
        "gia": 800000
    },
    {
        "id": 9,
        "ten_sp": "SƠ MI HỌA TIẾT REN",
        "mo_ta": "Với sự kết hợp tuyệt vời giữa chất liệu cao cấp, kiểu dáng thoải mái nhưng không kém phần nổi bật nhờ những họa tiết ren đẹp mắt, chiếc áo sơ mi sẽ giúp người diện trở nên nổi bật và tự tin hơn trong mọi dịp.Chất liệu sợi vải mềm mịn, thoáng mát được tuyển chọn cẩn thận để đảm bảo sự thoải mái tuyệt đối khi mặc vào. Kiểu dáng áo dài thướt tha sẽ tôn lên vẻ đẹp sang trọng. Đặc biệt, hoa văn ren được điểm trên thân áo, may nổi trên nền vải sẽ tăng thêm vẻ nhã nhặn và quý phái cho chiếc áo.Nhờ thiết kế tỉ mỉ đến từng đường may, hàng khuy đính kèm, đây sẽ là lựa chọn hoàn hảo cho các buổi tiệc, sự kiện hay những buổi gặp gỡ công việc hoặc cuộc hẹn cuối tuần.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/s1.webp",
        "anh_2": "../images/s2.webp",
        "anh_3": "../images/s3.webp",
        "anh_4": "../images/s4.webp",
        "gia": 650000
    },
    {
        "id": 10,
        "ten_sp": "ÁO TRỄ VAI DÁNG CROPTOP",
        "mo_ta": "Áo 2 dây kiểu dáng trễ vai lạ mắt. Tay áo may chun phồng thắt nơ phía trước thêm phần điệu đà nữ tính.Chất liệu vải thô 1 lớp bền màu, giữ phom hiệu quả. Kiểu dáng mới mẻ cùng với gam màu độc lạ tạo nên sức hút đặc biệt với bất kì quý cô nào. Với chiếc áo trễ vai này, nàng có thể thỏa thích biến đổi phong cách thời trang bằng cách kết hợp với nhiều món đồ khác nhau như quần tây, chân váy,... tùy theo phong cách của bản thân hay tùy theo các hoàn cảnh khác nhau.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/v1.webp",
        "anh_2": "../images/v2.webp",
        "anh_3": "../images/v3.webp",
        "gia": 450000
    },
    {
        "id": 11,
        "ten_sp": "ÁO SƠ MI TAY CÁNH TIÊN",
        "mo_ta": "Áo sơ mi cổ tròn dáng xuông. Tay liền tạo kiểu cánh tiên mềm mại kết hợp các đường xếp ly nhỏ, tinh tế thể hiện vẻ đẹp dịu dàng.  Thết kế áo sơ mi nữ với chất liệu lụa bóng mềm mại, thoáng mát, kiểu dáng áo xuông rộng rãi. Mẫu áo vừa tôn lên nét đẹp thanh lịch vừa mang nét đẹp trẻ trung, năng động phù hợp với thời tiết ngày hè. Nàng có thể dễ dàng kết hợp mãu áo sơ mi này cùng chân váy, quần sooc hoặc quần jeans để diện đi làm.",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/m1.webp",
        "anh_2": "../images/m2.webp",
        "anh_3": "../images/m3.webp",
        "gia": 650000
    },
    {
        "id": 12,
        "ten_sp": "ÁO THUN CUT - OUT LƯNG",
        "mo_ta": "Áo thun Oversize, dáng suông, cổ tròn, tay ngắn. Áo phối màu pastel nổi bật phía trước, năng động, hiện đại, thời trang. Thân sau áo được cut - out hai khuyết tạo kiểu độc đáo.Bạn có thể mix cùng chân váy, quần jeans, quần short là đã có ngay 1 outfít đường phố hiện đại. ",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/t1.webp",
        "anh_2": "../images/t2.webp",
        "anh_3": "../images/t3.webp",
        "gia": 550000
    },
    {
        "id": 13,
        "ten_sp": "ÁO THUN KHUYẾT CỔ",
        "mo_ta": "Áo thun basic, dáng suông, cổ tròn, tay ngắn. Thân trước áo được tạo khuyết gần cổ áo, độc đáo.Bạn có thể mix cùng chân váy, quần jeans, quần short là đã có ngay 1 outfít đường phố hiện đại. ",
        "loai_san_pham": "ÁO",
        "anh_1": "../images/k1.webp",
        "anh_2": "../images/k2.webp",
        "anh_3": "../images/k3.webp",
        "gia": 430000
    },
    {
        "id": 14,
        "ten_sp": "ÁO BLAZER CÔNG SỞ TAY NGẮN",
        "mo_ta": "Áo blazer là thiết kế hoàn hảo dành cho các cô nàng công sở đang tìm kiếm bộ trang phục trẻ trung, cá tính nhưng vẫn giữ được nét lịch sự, duyên dáng.Thiết kế kế thừa vẻ đẹp của phom dáng cổ điển, cách điệu thêm sự phóng khoáng qua dáng tay ngắn. Mix cùng MS 20M8698 để tạo set bộ thời trang và hiện đại. Sản phẩm kết hợp từ 3 dòng chất liệu Rayon, Poly, Spandex cao cấp, mang đến kết cấu mịn, thoải mái, tạo cảm  giác mềm mại khi chạm vào. Ngoài ra, chất liệu có độ rủ tự nhiên và  khả năng chống thấm nước, thoáng khí mát mẻ dành cho mùa hè.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/z1.webp",
        "anh_2": "../images/z2.webp",
        "anh_3": "../images/z3.webp",
        "gia": 1150000
    },
    {
        "id": 15,
        "ten_sp": "KAYLIN BLAZER - ÁO BLAZER THÊU LOGO",
        "mo_ta": "Thiết kế áo vest, blazer được kế thừa vẻ đẹp của form dáng áo vest cổ điển: cổ 2 ve, vai độn, dáng suông. Chất liệu tuysi mềm nhẹ, thoáng mát, ít nhăn và giữ form dáng tốt. Tất cả đã tạo nên cấu trúc thanh lịch, sang trọng mà vẫn đảm bảo tính thoải mái.Không chỉ đẹp từ thiết kế đến chất liệu, set đồ còn mang tính ứng dụng cao, phù hợp cho các cô nàng diện nơi công sở và đi dự sự kiện. ",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/ka1.webp",
        "anh_2": "../images/ka2.webp",
        "anh_3": "../images/ka3.webp",
        "gia": 950000
    },
    {
        "id": 16,
        "ten_sp": "ÁO BLAZER DAHLIA SET",
        "mo_ta": "Áo blazer lên dáng cổ V, tay ngắn, form suông thoải mái. Thiết kế được dệt điểm hoa tạo hiệu ứng mắt mắt, điểm nhấn cho bộ trang phục. Item thành công kế thừa vẻ đẹp của phom dáng cổ điển cũng như cách điệu thêm sự phóng khoáng, hiện đại. Sản phẩm kết hợp từ 2 dòng chất liệu Rayon, Poly cao cấp, mang đến kết cấu mịn, thoải mái, tạo cảm  giác mềm mại khi chạm vào. Ngoài ra, chất liệu có độ rủ tự nhiên và  khả năng chống thấm nước, thoáng khí mát mẻ dành cho mùa hè.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/da1.webp",
        "anh_2": "../images/da2.webp",
        "anh_3": "../images/da3.webp",
        "gia": 899000
    },
    {
        "id": 17,
        "ten_sp": "ÁO KHOÁC BOMBER IVY YOU",
        "mo_ta": "Áo khoác dáng bomber, tay dài bo gấu. Có 2 túi chéo có khóa kéo. Bo gân co giãn ở cổ và gấu tay áo. Cài bằng khóa kéo phía trước. Bên phải thêu logo IVY you. Chất vải thun dày dặn có lớp lót bên trong. Mix cùng quần jogger, quần jeans để có set đồ phong cách và năng động nhất.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/i1.webp",
        "anh_2": "../images/i2.webp",
        "anh_3": "../images/i3.webp",
        "anh_4": "../images/i4.webp",
        "gia": 650000
    },
    {
        "id": 18,
        "ten_sp": "POWER SUIT IN BLACK",
        "mo_ta": "Thiết kế cách điệu lạ mắt, tạo nên vẻ đẹp gợi cảm, xinh đẹp cuốn hút ánh nhìn của mọi người. Màu đen - sắc màu ‘vĩnh cửu’ trong làng thời trang. Với Power Suit, sắc đen đem đến phong thái quyến rũ, mạnh mẽ và sang trọng tuyệt đối cho các quý cô",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/p1.webp",
        "anh_2": "../images/p2.webp",
        "anh_3": "../images/p3.webp",
        "gia": 650000
    },
    {
        "id": 19,
        "ten_sp": "SET BỘ ÁO KIỂU VÀ CHÂN ZUÝP A",
        "mo_ta": "Thiết kế set bộ gồm áo blazer croptop trẻ trung và chân zuýp A ngắn hiện đại đã đáp ứng đủ tình thần tươi mới, năng động nhưng vẫn thật thanh lịch và tinh tế.Áo blazer được thiết kế cách điệu cổ tròn, tay ngắn, có 4 túi nhỏ và dấu khuy. Dáng váy chân A nhẹ ôm cơ thể, độ dài trên gối, hack dáng cũng như che khuyết điểm cực tốt. Set bộ lựa chọn mix màu pastel nhẹ nhàng nhưng vẫn đủ nổi bật để nàng tỏa sáng. Bạn có thể diện set bộ đi làm, đi họp hay đến những nơi vui chơi, gặp mặt bạn bè. ",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/se1.webp",
        "anh_2": "../images/se2.webp",
        "anh_3": "../images/se3.webp",
        "gia": 999000
    },
    {
        "id": 20,
        "ten_sp": "ÁO GILE DẠ TWEED",
        "mo_ta": "Áo gile croptop là một phiên bản ngắn gọn của áo gile, thường để mix tạo điểm nhấn với áo, chân váy hay nhiều thiết kế khác.Áo dáng ngắn, cổ chữ V, tay sát nách tạo nên vẻ đẹp quyến rũ và hiện đại.Trong thời tiết lạnh, bạn có thể mặc một áo thun dài tay hoặc áo len dưới áo gile vừa để giữ ấm cơ thể vừa biến tấu thành Outfit thời thượng. ",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/gi1.webp",
        "anh_2": "../images/gi2.webp",
        "anh_3": "../images/gi3.webp",
        "gia": 450000
    },
    {
        "id": 21,
        "ten_sp": "ÁO KIỂU ELYSIA SET",
        "mo_ta": "Bản phối trẻ trung nhưng vẫn thời thượng và sang trọng dành cho nàng công sở mùa thu này hãy gọi tên Elysia Set. Set bộ được mix từ áo vest kiểu, dáng Croptop cùng chân váy xếp li. Áo vest Croptop, kiểu dáng trẻ trung năng động với thiết kế tay ngắn bên cạnh cầu vai bồng. Thân trước cách điệu cổ V nhẹ nhàng, đính 4 khuy sang trọng.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/el1.webp",
        "anh_2": "../images/el2.webp",
        "anh_3": "../images/el3.webp",
        "gia": 550000
    },
    {
        "id": 22,
        "ten_sp": "ÁO VEST KIỂU FRENCH (KÈM ÁO CROPTOP)",
        "mo_ta": "Set đồ bao gồm Áo blazer cộc tay cùng áo croptop để tạo nên một bộ trang phục hoàn hảo cho các buổi hẹn hò, tiệc tùng hay đi làm.Áo blazer ngắn tay phong cách có thiết kế đơn giản nhưng không kém phần tinh tế, với đường bó chun eo cách điệu, tôn lên vẻ ngoài gọn gàng và thời trang. Chất liệu vải mềm mại và thoáng mát giúp bạn cảm thấy thoải mái trong suốt ngày dài.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/fr1.webp",
        "anh_2": "../images/fr2.webp",
        "anh_3": "../images/fr3.webp",
        "gia": 890000
    },
    {
        "id": 23,
        "ten_sp": "OMBRÉ SET - ÁO VEST DÁNG NGẮN VÀ QUẦN SHORT",
        "mo_ta": "Áo khoác dáng vest, tay ngắn. Phía trước có 2 khuy cài kim loại và túi hộp. Chất liệu voan mềm có độ xuyên thấu nhẹ. Phối màu Ombré độc quyền Quần short dáng suông, độ dài ngang đùi. Phía trước có khuy cài giống áo vest và khóa kéo. Phối màu trơn. Kèm quần màu ngẫu nhiên (Cam hoặc Ghi khói)",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/o1.webp",
        "anh_2": "../images/o2.webp",
        "anh_3": "../images/o3.webp",
        "gia": 1050000
    },
    {
        "id": 24,
        "ten_sp": "ELEGANT PLEATED",
        "mo_ta": "Áo vest cổ bẻ 2 ve cách điệu, khoét chữ K độc đáo. Tay áo dài. Đệm vai. Tà đáp chéo có 1 khuy cài. Xẻ phía trước. 2 viền túi 2 bên. Dập ly trở thành xu hướng kéo dài suốt 3 mùa mốt vừa qua. chi tiết dập ly kết hợp cùng áo vest thắt nơ eo tạo nên sự uyển chuyển trong từng cử động",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/ga1.webp",
        "anh_2": "../images/ga2.webp",
        "anh_3": "../images/ga3.webp",
        "gia": 950000
    },
    {
        "id": 25,
        "ten_sp": "TWEED JACKET DÁNG LỬNG",
        "mo_ta": "Áo vest dáng lửng cổ tròn. Tay lỡ. Viền bằng vải vặn thừng màu trắng. Có 2 túi vuông phía trước, viền túi khác màu tạo nổi bật. Có thể mix cùng đầm đồng bộ. Với độ dài trên eo cùng dáng kẻ trẻ trung. Các nhà mốt của IVY moda đan xen và chơi màu trên những sợi len nguyên chất để tạo nên sắc xanh giúp nàng tôn lên vẻ đẹp sang trọng mà vẫn giữ được sự cổ điển trong từng thiết kế.",
        "loai_san_pham": "ÁO KHOÁC",
        "anh_1": "../images/j1.webp",
        "anh_2": "../images/j2.webp",
        "anh_3": "../images/j3.webp",
        "gia": 750000
    },
    {
        "id": 26,
        "ten_sp": "CHÂN VÁY BÚT CHÌ XẺ LỆCH",
        "mo_ta": "Nếu nàng đang theo đuổi phong cách thời trang bền vững chắc chắn không thể thiếu thiết kế chân bút chì này trong tủ đồ của mình.Thân trước xẻ lệch 1 bên, độ dài qua đầu gối và cài bằng khóa kéo. Chân váy kiểu dáng bút chì cơ bản dễ dàng mix&match với nhiều kiểu áo khác nhau.Thiết kế hoàn hảo để nàng xuất hiện đủ chỉn chu và lịch sự. ",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/ch1.webp",
        "anh_2": "../images/ch2.webp",
        "anh_3": "../images/ch3.webp",
        "gia": 350000
    },
    {
        "id": 28,
        "ten_sp": "CHÂN VÁY BÚT CHÌ BÈO NHÚN",
        "mo_ta": "Thiết kế chân váy 2 lớp, cạp cao, dáng bút chì ôm gọn, dễ dàng tôn lên vóc dáng người mặc. Đặc biệt, chân váy đã sử dụng kỹ thuật dệt burn out để tạo nên họa tiết hoa văn độc đáo trên thân trước, giúp thiết kế trở nên nổi bật hơn. Bên cạnh đó, với chất liệu Chiffon, chân váy mang đến sự mềm mại, bóng nhẹ, tạo cảm giác thân thiện và thoải mái. Vải không bị nhàu, nhăn hay co trong khi sử dụng. Cảm giác mát mẻ, thoáng khí khi trải nghiệm trong mùa hè.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/n1.webp",
        "anh_2": "../images/n2.webp",
        "anh_3": "../images/n3.webp",
        "gia": 350000
    },
    {
        "id": 29,
        "ten_sp": "CHÂN VÁY TUYSI 1 LỚP ( THÊM ĐAI KIỂU )",
        "mo_ta": "Chân váy kiểu dáng bút chì, phù hợp với nhiều dáng vóc, tôn lên phần eo và che đi một cách nhẹ nhàng các khuyết điểm cơ thể. Chiều dài chân váy qua gối, thiết kế tà xếp tạo điểm nhấn cũng như thêm phần nữ tính và thoải mái. Phần eo mix đai kiểu hiện đại. ",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/l1.webp",
        "anh_2": "../images/l2.webp",
        "anh_3": "../images/l3.webp",
        "gia": 300000
    },
    {
        "id": 30,
        "ten_sp": "ZUÝP A NGẮN XẾP TÀ",
        "mo_ta": "Thiết kế chân váy chữ A, độ dài trên gối, trẻ trung và năng động. Chân váy 2 lớp, thiết kế xếp tà chéo kết hợp phần túi sườn tạo điểm nhấn. Chất liệu Tuysi dày dặn, đứng form, thoải mái khi mặc. Nàng dễ dàng mix&match cùng nhiều kiểu áo khác nhau để tạo nên phong cách thời trang cho riêng mình. ",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/zu1.webp",
        "anh_2": "../images/zu2.webp",
        "anh_3": "../images/zu3.webp",
        "gia": 400000
    },
    {
        "id": 31,
        "ten_sp": "CHÂN VÁY A KHAKI XẾP LY",
        "mo_ta": "Chân váy xếp ly dáng xoè là một sản phẩm thời trang đẹp mắt và nữ tính, được thiết kế để tôn lên vẻ đẹp của người diện. Với sự kết hợp giữa chất liệu vải Khaki đứng dáng và độ rộng của ly xếp, chiếc váy này mang đến cảm giác thoải mái và nền nã khi mặc.Thiết kế này cũng giúp tôn lên đôi chân thon dài và mang đến sự tự tin cho phái đẹp khi diện váy.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/kh1.webp",
        "anh_2": "../images/kh2.webp",
        "anh_3": "../images/kh3.webp",
        "gia": 299000
    },
    {
        "id": 32,
        "ten_sp": "CHÂN VÁY TUYSI XẾP LY",
        "mo_ta": "Chân váy xếp ly dáng xoè là một sản phẩm thời trang đẹp mắt và nữ tính, được thiết kế để tôn lên vẻ đẹp của người diện. Với sự kết hợp giữa chất liệu vải Khaki đứng dáng và độ rộng của ly xếp, chiếc váy này mang đến cảm giác thoải mái và nền nã khi mặc.Thiết kế này cũng giúp tôn lên đôi chân thon dài và mang đến sự tự tin cho phái đẹp khi diện váy.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/y1.webp",
        "anh_2": "../images/y2.webp",
        "anh_3": "../images/y3.webp",
        "gia": 530000
    },
    {
        "id": 33,
        "ten_sp": "CHÂN VÁY A NGẮN VẠT CHÉO",
        "mo_ta": "Thiết kế chân váy dành cho nàng công sở yêu thích vẻ đẹp thanh lịch và tinh tế.Chân váy cạp cao, độ dài qua gối giúp che khuyết điểm tốt cũng như tôn lên vẻ đẹp dịu dàng cho người mặc.Thiết kế xếp ly mềm mại, tạo độ xòe nhẹ, uyển chuyển trên từng bước đi. ",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/ng1.webp",
        "anh_2": "../images/ng2.webp",
        "anh_3": "../images/ng3.webp",
        "gia": 299000
    },
    {
        "id": 34,
        "ten_sp": "CHÂN VÁY MIDI FLOWER SET",
        "mo_ta": "Thiết kế chân váy dành cho nàng công sở yêu thích vẻ đẹp thanh lịch và tinh tế.Chân váy cạp cao, độ dài qua gối giúp che khuyết điểm tốt cũng như tôn lên vẻ đẹp dịu dàng cho người mặc.Thiết kế xếp ly mềm mại, tạo độ xòe nhẹ, uyển chuyển trên từng bước đi.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/fl1.webp",
        "anh_2": "../images/fl2.webp",
        "anh_3": "../images/fl3.webp",
        "anh_4": "../images/fl4.webp",
        "gia": 350000
    },
    {
        "id": 35,
        "ten_sp": "CHÂN VÁY JEANS PHỐI KHUY",
        "mo_ta": "Chân váy dáng A, màu sắc basic trẻ trung,tạo điểm nhấn qua đường xếp vạt chéo thân trước. Váy cạp cao, độ dài trên gối, giúp tôn dáng vóc người mặc. Chất liệu chính của váy là Tuysi, mang đặc điểm nhẹ, thoáng mát, dễ chịu, thích hợp thời tiết Xuân - Hè.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/X1.webp",
        "anh_2": "../images/X2.webp",
        "anh_3": "../images/X3.webp",
        "anh_4": "../images/X4.webp",
        "gia": 399000
    },
    {
        "id": 36,
        "ten_sp": "ZUÝP BÒ CHLOE",
        "mo_ta": "Chân váy cạp cao, 2 lớp, độ dài qua gối. Thiết kế dáng xòe nhẹ, che khuyết điểm tốt. Thiết kế được dệt may từ 2 dòng chất liệu Viscose, Poly cao cấp. Sử dụng kỹ thuật dệt burn out để tạo nên nền họa tiết vẽ tay độc quyền. Sản phẩm có độ mịn màng cao, khi mặc vô cùng  thoải mái và không hề cảm nhận sự bí bách. Lựa chọn dễ chịu trong thời tiết Xuân – Hè.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/R1.webp",
        "anh_2": "../images/R2.webp",
        "anh_3": "../images/R3.webp",
        "anh_4": "../images/R4.webp",
        "gia": 299000
    },
    {
        "id": 37,
        "ten_sp": "CHÂN VÁY JEANS DÁNG DÀI",
        "mo_ta": "Mang đến kiểu dáng midi hiện đại trong chất liệu demin bền bỉ, chiếc chân váy mang lại tính linh hoạt trong việc phối đồ, giúp bạn dễ dàng thể hiện phong cách cá nhân.Thiết kế tạo điểm nhấn qua hàng khuy nổi trên thân trước kết hợp túi kiểu và đường may nổi độc đáo.",
        "loai_san_pham": "CHÂN VÁY",
        "anh_1": "../images/U1.webp",
        "anh_2": "../images/U2.webp",
        "anh_3": "../images/U3.webp",
        "anh_4": "../images/U4.webp",
        "gia": 400000
    },
    {
        "id": 38,
        "ten_sp": "MERMAID DRESS - ĐẦM VAI CHỜM",
        "mo_ta": "Tủ đồ nàng năng động mùa hè này chắc chắn không thể thiếu chiếc Zuýp cân mọi phong cách thời trang. Thiết kế chân váy dáng A nhẹ, độ dài trên gối, trẻ trung, cá tinh. Nàng có thể lựa chọn chân váy mix cùng nhiều kiểu áo khác nhau để tạo nét đẹp riêng mình. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/de1.webp",
        "anh_2": "../images/de2.webp",
        "anh_3": "../images/de3.webp",
        "anh_4": "../images/de4.webp",
        "gia": 850000
    },
    {
        "id": 39,
        "ten_sp": "ĐẦM CỔ K PHỐI VOAN",
        "mo_ta": "Một chiếc chân váy jeans trong tủ quần áo sẽ mang lại tính linh hoạt trong việc phối đồ, giúp bạn dễ dàng thể hiện phong cách cá nhân.Chân váy có kiểu dáng midi hiện đại, trên nền chất liệu demin cao cấp với đặc tính dày và bên. Thiết kế tạo điểm nhấn qua các chi tiết như túi, nút, khuy, và đường may nổi độc đáo.Bạn dễ dàng kết hợp chân váy với nhiều loại trang phục khác nhau, từ áo sơ mi, áo thun, áo len đến áo khoác để biến tấu thành một Outfits phù hợp với phong cách cá nhân.",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/ko1.webp",
        "anh_2": "../images/ko2.webp",
        "anh_3": "../images/ko3.webp",
        "gia": 550000
    },
    {
        "id": 40,
        "ten_sp": "ĐẦM HOA DÁNG A",
        "mo_ta": "White Woven là sản phẩm thời trang sành điệu và nổi bật được phối hợp giữa áo sơ mi kiểu và chân váy ngắn chữ A. Chất liệu vải Tencel đồng bộ tạo cảm giác mềm mại và rất dễ chịu khi mặc.Áo của Woven set với thiết kế cổ đức cùng điểm nhấn nổi bật là phần xếp ly vai tạo sự quyến rũ và thu hút.Chân váy được may theo dáng chữ A, có độ dài trên gối mang đến sự trẻ trung và năng động. Phía sau chân váy được trang bị khoá kéo tiện dụng, cùng đường may dây đan xen ở cạp tạo điểm nhấn, giúp bộ đồ trở nên phá cách và cá tính hơn.",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/ho1.webp",
        "anh_2": "../images/ho2.webp",
        "anh_3": "../images/ho3.webp",
        "gia": 600000
    },
    {
        "id": 41,
        "ten_sp": "ĐẦM TWILL TẠO KIỂU",
        "mo_ta": "Youthful Set với thiết kế trẻ trung, hiện đại nhưng vẫn thời thượng và sang trọng dành cho nàng công sở thêm vào tủ đồ Xuân - Hè của mình. Set bộ gồm áo vest kiểu kết hợp cùng chân váy xếp ly. Áo cổ V, ngắn tay, kiểu dáng Croptop, được cài bằng khuy bọc. Thiết kế mix cùng MS 31M8688 để tạo set hoàn chỉnh. Sản phẩm kết hợp từ 3 dòng chất liệu Rayon, Poly, Spandex cao cấp, mang đến kết cấu mịn, thoải mái, tạo cảm  giác mềm mại khi chạm vào. Ngoài ra, chất liệu có độ rủ tự nhiên và  khả năng chống thấm nước, thoáng khí mát mẻ dành cho mùa hè.",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/tw1.webp",
        "anh_2": "../images/tw2.webp",
        "anh_3": "../images/tw3.webp",
        "gia": 650000
    },
    {
        "id": 42,
        "ten_sp": "TESSA DRESS - ĐẦM LỤA XÒE ĐAI EO",
        "mo_ta": "Đón Xuân - Hè qua dòng chất liệu lụa cao cấp để cảm nhận sự mềm mại, nhẹ nhàng trên từng điểm chạm. Dark Beige Set được tạo nên từ thiết kế sơ mi cổ điển bên cạnh dáng chân váy xếp ly thời thượng. Áo sơ mi cổ đức, ngắn tay gập gấu cách điệu, thân trước cố đính qua hàng khuy kim loại sang trọng. Chân váy xếp ly độ dài qua gối, tạo độ bồng nhẹ, đặc biệt che khuyết điểm cực tốt.  Thiết kế trẻ trung, hiện đại nhưng vẫn thời thượng và sang trọng dành cho nàng công sở thêm vào tủ đồ Xuân - Hè của mình.",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/sa1.webp",
        "anh_2": "../images/sa2.webp",
        "anh_3": "../images/sa3.webp",
        "anh_4": "../images/sa4.webp",
        "gia": 450000
    },
    {
        "id": 44,
        "ten_sp": "ELLA DRESS - ĐẦM SUÔNG CÁNH TIÊN",
        "mo_ta": "Thiết kế set bộ với áo blazer cùng quần short cá tính là lựa chọn hoàn hảo dành cho cô nàng công sở đang tìm kiếm sự trẻ trung, cá tính nhưng vẫn đảm bảo tính chuyên nghiệp, lịch sự khi đi làm. Bản phối Dahlia Set từ MS 67M8817 kết hợp MS 20M8817 sẽ là một gợi ý từ IVY moda cho tủ đồ Xuân - Hè của nàng. Áo blazer lên dáng cổ V, tay ngắn, form suông thoải mái. Thiết kế được dệt điểm hoa tạo hiệu ứng mắt mắt, điểm nhấn cho bộ trang phục. Item thành công kế thừa vẻ đẹp của phom dáng cổ điển cũng như cách điệu thêm sự phóng khoáng, hiện đại. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/ela1.webp",
        "anh_2": "../images/ela2.webp",
        "anh_3": "../images/ela3.webp",
        "gia": 700000
    },
    {
        "id": 45,
        "ten_sp": "ĐẦM SƠ MI KẺ",
        "mo_ta": "Bản phối trẻ trung nhưng vẫn thời thượng và sang trọng dành cho nàng công sở mùa thu này hãy gọi tên Elysia Set. Set bộ được mix từ áo vest kiểu, dáng Croptop cùng chân váy xếp li. Áo vest Croptop, kiểu dáng trẻ trung năng động với thiết kế tay ngắn bên cạnh cầu vai bồng. Thân trước cách điệu cổ V nhẹ nhàng, đính 4 khuy sang trọng. Lựa chọn mix cùng MS 31M8445 để tạo set bộ hoàn hảo. Elysia Set sử dụng chất liệu Tuysi cao cấp, mang đến cảm giác mặc thoải mái và thích hợp với mọi thời tiết. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/mi1.webp",
        "anh_2": "../images/mi2.webp",
        "anh_3": "../images/mi3.webp",
        "gia": 499000
    },
    {
        "id": 46,
        "ten_sp": "LIGHT SPRING MIDI DRESS - ĐẦM LỤA CỔ KIỂU",
        "mo_ta": "Set bộ Expert nằm trong BST MOMENT OF BLISS với tôn chỉ đẹp không chỉ về ngoại hình mà còn là lời bày tỏ từ giá trị đích thực, một bản hòa ca đầy cảm xúc trong những ngày cuối năm ấm áp.IVY moda tái hiện vẻ đẹp qua gam màu ghi trung tính, biến tấu set bộ trẻ trung hiện đại khiến nàng nổi bật và tỏa sáng theo cách riêng biệt mà chẳng cần lớp filter lấp lánh nào khác.Áo sơ mi croptop cổ chữ V, tay ngắn, có đính kèm phụ kiện cài. Thiết kế hai lớp đan xen, thể hiện tính thời trang, giúp set bộ thêm phần điệu đà, đẹp mắt.Chân váy Midi độ dài qua gối  với phần cạp cao ôm gọn vòng 2 và vòng 3 cơ thể. Thiết kế che khuyết điểm tốt, cực kì tôn dáng. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/li1.webp",
        "anh_2": "../images/li2.webp",
        "anh_3": "../images/li3.webp",
        "gia": 450000
    },
    {
        "id": 47,
        "ten_sp": "ĐẦM ORGANZA TAY LIỀN",
        "mo_ta": "Điểm mới thiết kế trong BST Xuân -  Hè được IVY moda ra mắt đó là kỹ thuật dệt burn out hiện đại để tạo nên nền họa tiết vải độc đáo, thể hiện sự cao  sang của người mặc. Set đầm gồm áo Chiffon khoác kết hợp đầm xòe dệt họa tiết thời thượng. Áo khoác mỏng nhẹ, che bờ vai tinh tế, đủ thể hiện nét quyết rũ nhưng vẫn đảm bảo tính lịch sự, sang trọng trong môi trường công sở. Đầm thiết kế 2 dây cách điệu, thân trên ôm, thân dưới bán nguyệt xòe nhẹ. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/or1.webp",
        "anh_2": "../images/or2.webp",
        "anh_3": "../images/or3.webp",
        "gia": 600000
    },
    {
        "id": 48,
        "ten_sp": "ĐẦM LỤA CỔ ĐỨC DÁNG XÒE",
        "mo_ta": "Nàng nổi bật xuống phố với Set ren Fuchsia xinh đẹp và sành điệu. Thiết kế mang điểm chung phối ren độc đáo cùng sự kết hợp giữa 2 item áo sơ mi croptop cùng chân váy A hiện đại.Áo cổ đức, tay ngắn, tạo điểm nhấn đường viền trơn kèm khuy đính kim loại sang trọng. Chân váy A ren đồng bộ vừa mang đến sự thanh lịch, vừa giúp cô nàng tôn lên diện mạo trẻ trung và thời thượng.Mix cùng chiếc túi xách nhỏ xinh, phụ kiện trang sức, giày cao gót đi kèm để có những bức ảnh thật xinh đẹp. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/ua1.webp",
        "anh_2": "../images/ua2.webp",
        "anh_3": "../images/ua3.webp",
        "gia": 500000
    },
    {
        "id": 49,
        "ten_sp": "FUCHSIA DRESS - ĐẦM XÒE HỌA TIẾT",
        "mo_ta": "Set bộ thời trang IVY You cá tính, hiện đại gồm: Áo sơ mi cổ đức cách điệu cùng chân váy chữ A bắt mắt.Áo sơ mi có thiết kế tay ngắn, tạo điểm nhấn tinh tế với cổ đức, tạo nên sự thanh lịch. Áo giấu khuyết điểm với một dãy khuy che phần thân trước, thể hiện sự gọn gàng và trang nhã. Đặc biệt, phần gấu áo thiết kế dây rút, cho phép bạn biến tấu tùy theo sở thích của mình. Chân váy đi kèm là chữ A, độ dài trên đầu gối, tạo cảm giác thoải mái và dễ di chuyển. Bên cạnh đó, chiếc chân váy này còn được trang bị túi hộp, giúp bạn tiện lợi để đựng các vật dụng nhỏ. ",
        "loai_san_pham": "ĐẦM",
        "anh_1": "../images/fu1.webp",
        "anh_2": "../images/fu2.webp",
        "anh_3": "../images/fu3.webp",
        "gia": 650000
    },
    {
        "id": 50,
        "ten_sp": "DÉP CAO GÓT ĐẾ NHỰA",
        "mo_ta": "Thiết kế set bộ trẻ trung, năng động với áo blazer croptop cá tính bên cạnh dáng chân váy A basic, thời thượng.Biến tấu thiết kế blazer sang phiên bản cổ đức kín đáo, thân trước có hai vạt xếp lên nhau được cố định bằng khuy kim loại. Chân váy A độ dài trên gối, có phối đai nhỏ tạo điểm nhấn, hoàn hảo hack dáng cũng như che khuyết điểm cực tốt. ",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/nh1.webp",
        "anh_2": "../images/nh2.webp",
        "anh_3": "../images/nh3.webp",
        "gia": 250000
    },
    {
        "id": 51,
        "ten_sp": "XĂNG ĐAN DA CAO GÓT",
        "mo_ta": "Lace skirt là một bộ trang phục đầy nữ tính và quyến rũ, gồm một thiết kế áo và chân váy đồng bộ, được làm từ chất liệu vải ren cao cấp với họa tiết hoa in nổi tinh tế.Vải ren được may 2 lớp, đảm bảo sự thoải mái và độ bền trong quá trình sử dụng, bên trong có lớp lót giúp giữ cho sản phẩm vừa có nét thu hút, quyến rũ mà không bị quá phô trương.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/dr1.webp",
        "anh_2": "../images/dr2.webp",
        "anh_3": "../images/dr3.webp",
        "gia": 299000
    },
    {
        "id": 52,
        "ten_sp": "GIÀY BÚP BÊ RETRO",
        "mo_ta": "Đầm Tuysi cổ tàu, thiết kế vai chờm. Phần eo được nhấn các đường chun nhúm co giãn tạo kiểu. Tùng váy chứ A được xếp ly bồng nhẹ. Còn có hàng khuy kim loại  sang trọng  và thời thượng.Thiết kế này tạo hiệu ứng rất cuốn hút mỗi khi người mặc di chuyển. Đây là mẫu đầm hoàn hảo cho những ngày đi làm bận rộn, tan làm có thể trực tiếp diện đi cà phê, dạo phố với bạn bè.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/re1.webp",
        "anh_2": "../images/re2.webp",
        "anh_3": "../images/re3.webp",
        "anh_4": "../images/re4.webp",
        "gia": 320000
    },
    {
        "id": 53,
        "ten_sp": "XĂNG ĐAN CAO GÓT DÂY MẢNH",
        "mo_ta": "Thiết kế đầm kiểu mang vẻ đẹp thời thượng, sang trọng và tinh tế. Đầm thích hợp để diện đến nơi công sở, gặp mặt bạn bè hay đi tiệc. Đầm lựa chọn kiểu dáng A, phù hợp nhiều dáng người khác nhau, thân trên ôm và thân dưới A nhẹ. Cổ đầm lên dáng chữ K lịch sự, phần eo nẹp bản to đính thêm khuy tạo điểm nhấn. Tay đầm phối voan, mang đến sự mềm mại, nhẹ nhàng. Nàng hãy mix thêm giày cao gót cùng chiếc túi sách nhỏ để có ngay Outfit xu hướng. ",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/ma1.webp",
        "anh_2": "../images/ma2.webp",
        "anh_3": "../images/ma3.webp",
        "gia": 299000
    },
    {
        "id": 54,
        "ten_sp": "TÚI DA ĐEO VAI",
        "mo_ta": "Nàng nhhẹ nhàng, mềm mại trong thiết kế đầm hoa yêu kiều. Đầm cổ thuyền, có độ dài qua gối cùng kiểu dáng chữ A quen thuộc, khéo léo tôn lên nét đẹp dịu dàng của người mặc. Thiết kế tạo điểm nhấn thắt đai ngang eo, giúp che khuyết điểm tốt. Chất liệu tơ voan mềm mại tạo cảm giác dễ chịu khi tiếp xúc với da cũng như giúp bạn luôn cảm thấy thoải mái và mát mẻ trong suốt cả ngày dài.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/va1.webp",
        "anh_2": "../images/va2.webp",
        "anh_3": "../images/va3.webp",
        "anh_4": "../images/va4.webp",
        "gia": 350000
    },
    {
        "id": 55,
        "ten_sp": "CLUTCH NỮ CAO CẤP",
        "mo_ta": "Phông còn dáng cổ tròn thường thấy, cổ đầm đã được điểm thêm 1 đường xẻ nhẹ giúp tạo điểm nhấn cũng như mang đến đôi chút quyến rũ, tự tin. Đầm tay ngắn, cắt vát kiểu hiện đại. Phần eo ôm đứng form che khuyết điểm. Còn thân dưới xếp ly bồng nhẹ. Đầm sử dụng chất vải Twill dày dặn, không nhăn mang lại cảm giác thoải mái mà vẫn giữ được nét thanh lịch, lịch sự. Thiết kế đầm có tính ứng dụng cao, là món đồ không thể thiếu cho dịp sang Thu này.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/cl1.webp",
        "anh_2": "../images/cl2.webp",
        "anh_3": "../images/cl3.webp",
        "gia": 299000
    },
    {
        "id": 56,
        "ten_sp": "TÚI MINIBAG CHẦN CHỈ",
        "mo_ta": "Đầm lụa xòe đai eo (Tessa Dress) là sự kết hợp hoàn hảo giữa sang trọng và thoải mái, giúp bạn tự tin tỏa sáng trong mọi hoàn cảnh. Với một chút tinh tế trong cách phối đồ và chọn phụ kiện, bạn sẽ luôn nổi bật và cuốn hút.Thiết kế lựa chọn chất liệu lụa gân mềm mại, tạo cảm giác mặc êm dịu, nhẹ nhàng trên da. Bên cạnh đó, vải còn có các điểm vân bắt sáng, giúp đầm nổi bật hơn khi diện vào buổi tối. ",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/ci1.webp",
        "anh_2": "../images/ci2.webp",
        "anh_3": "../images/ci3.webp",
        "anh_4": "../images/ci4.webp",
        "gia": 300000
    },
    {
        "id": 57,
        "ten_sp": "TÚI ĐEO VAI BAGUETTE",
        "mo_ta": "Nằm trong BST Xuân - Hè mới nhất, thiết kế đầm kiểu đáp ứng đầy đủ các yếu tố từ thanh lịch, nhẹ nhàng đến sang trọng và thời thượng mà nàng công sở đang cần. Đầm xèo cổ V, thiết kế tay ngắn thời trang. Phần eo ôm nhẹ, kèm đai, tôn dáng. Tùng váy xếp ly, tạo độ xòe. Thiết kế tạo hiệu ứng cuốn hút mỗi khi người mặc di chuyển. Đây là mẫu đầm hoàn hảo cho những ngày đi làm bận rộn, tan làm có thể trực tiếp diện đi cà phê, dạo phố với bạn bè.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/et1.webp",
        "anh_2": "../images/et2.webp",
        "anh_3": "../images/et3.webp",
        "anh_4": "../images/et4.webp",
        "gia": 250000
    },
    {
        "id": 58,
        "ten_sp": "TÚI XÁCH CHẦN BÔNG",
        "mo_ta": "Đầm dáng suông, không ôm sát cơ thể, tạo sự thoải mái và che khuyết điểm cực tốt. Thiết kế cổ tròn, tay ngắn với phần đính khuy tạo điểm nhấn đã làm cho trang phục trở nên độc đáo hơn. Thiết kế lựa chọn chất liệu Chiffon được dệt từ những sợi tơ tự nhiên để mang đến sản phẩm sự mềm mại, bóng nhẹ, tạo cảm giác thân thiện và thoải mái. ",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/bo1.webp",
        "anh_2": "../images/bo2.webp",
        "anh_3": "../images/bo3.webp",
        "anh_4": "../images/bo4.webp",
        "gia": 400000
    },
    {
        "id": 59,
        "ten_sp": "TÚI XÁCH HOBO",
        "mo_ta": "Đầm lụa cổ đức, thiết kế tay lửng cùng họa tiết kẻ bắt mắt. Phần eo tạo điểm nhấn qua đường chun nhúm co giãn. Tùng váy dáng A nhẹ. Còn có hàng khuy kim loại  sang trọng  và thời thượng.Thiết kế này tạo hiệu ứng rất cuốn hút mỗi khi người mặc di chuyển. Đây là mẫu đầm hoàn hảo cho những ngày đi làm bận rộn, tan làm có thể trực tiếp diện đi cà phê, dạo phố với bạn bè.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/xa1.webp",
        "anh_2": "../images/xa2.webp",
        "anh_3": "../images/xa3.webp",
        "gia": 450000
    },
    {
        "id": 60,
        "ten_sp": "TÚI HỘP MINI PHỐI XÍCH",
        "mo_ta": "Nằm trong BST URBAN CHIC khởi đầu cho SPRING/SUMMER 2024 NEW COLLECTION, thiết kế mang sứ mệnh tạo nên sự biến chuyển linh hoạt của thời trang mới. Để xây dựng kết nối về cảm xúc, tâm trí thông qua những điểm chạm dịu dàng từ chất vải mềm mại, phom dáng tinh chỉnh vừa vặn và đem đến sự thoải mái êm dịu.Light Spring lên dáng bán nguyệt nhẹ nhàng, nổi bật trong gam màu tươi sáng, sẵn sàng thể hiện vẻ đẹp ngọt ngào và lãng mạn.",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/ni1.webp",
        "anh_2": "../images/ni2.webp",
        "anh_3": "../images/ni3.webp",
        "anh_4": "",
        "gia": 390000
    },
    {
        "id": 61,
        "ten_sp": "BALO DA KẺ CARO",
        "mo_ta": "Đầm hai lớp, có độ dài qua gối, thiết kế xếp li tạo độ xoè nhẹ, vừa che khuyết điểm tốt vừa tăng thêm phần dịu dàng. Thiết kế được tạo nên trên nền chất liệu lụa mềm mại, mang đến cảm giác mặc thoải mái, thích hợp mọi thời tiết. ",
        "loai_san_pham": "PHỤ KIỆN",
        "anh_1": "../images/ke1.webp",
        "anh_2": "../images/ke2.webp",
        "anh_3": "../images/ke3.webp",
        "anh_4": "../images/ke4.webp",
        "gia": 350000
    },
    {
        "id": 62,
        "ten_sp": "QUẦN SHORT PHỐI LY NỔI",
        "mo_ta": "Đầm lụa cổ đức, thiết kế tay ngắn thời trang. Phần eo ôm nhẹ, tôn dáng. Tùng váy xếp ly, tạo độ xòe. Thân trước đính hàng khuy kim loại sang trọng. Thiết kế được may cắt từ 2 dòng chất liệu Tencel, Nylon cao cấp, hút ẩm tốt nên khi mặc vô cùng  thoải mái,  không hề cảm nhận sự bí bách. Bề mặt mịn màng, mềm mại, tạo cảm giác thoáng mát, dễ chịu trong thời tiết Xuân – Hè.",
        "loai_san_pham": "QUẦN",
        "anh_1": "../images/so1.webp",
        "anh_2": "../images/so2.webp",
        "anh_3": "../images/so3.webp",
        "anh_4": "../images/so4.webp",
        "gia": 250000
    },
    {
        "id": 63,
        "ten_sp": "QUẦN SHORT BASIC ỐNG SUÔNG",
        "mo_ta": "Fuchsia lên dáng bán nguyệt nhẹ nhàng, nổi bật trong nền họa tiết thời thượng, sẵn sàng thể hiện vẻ đẹp sang trọng và cao sa. Đầm hai lớp, có độ dài qua gối, thiết kế xếp li tạo độ xoè nhẹ, vừa che khuyết điểm tốt vừa tăng thêm phần dịu dàng. ",
        "loai_san_pham": "QUẦN",
        "anh_1": "../images/su1.webp",
        "anh_2": "../images/su2.webp",
        "anh_3": "../images/su3.webp",
        "gia": 300000
    },
    
];